# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Deep Learning Seminar, Spring 2016, Dept. of Statistics, Seoul National University
email: 
description: > # this means to ignore newlines until "baseurl:"
    Deep learning seminar Spring 2016, Dept. of Statistics, Seoul National University. 
baseurl: "/dl-seminar" # the subpath of your site, e.g. /blog
url: "https://snu-stat.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  kose-y

# Build settings
markdown: kramdown

exclude:
    - _posts/2016-03-16-welcome-to-jekyll.markdown
